/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "google_auth.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(googleauth_MigrationPayload, googleauth_MigrationPayload, AUTO)


PB_BIND(googleauth_MigrationPayload_OtpParameters, googleauth_MigrationPayload_OtpParameters, AUTO)









